---
- name: Listen for events on a webhook
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:

    - name: Run Test Job
      condition: event.payload.test == 'yes'
      action:
        run_job_template:
          name: Demo Job Template
          organization: Default

    - name: Run CPU Remediation Job
      condition: event.payload.state == 'OPEN' and event.payload.text == 'CPU problem'
      action:
        run_workflow_template:
          name: '[WF] Remediate Cloud Machine CPU'
          organization: Default
          job_args:
            extra_vars:
              dynatrace_alert_severity: "{{ event.payload.severity }}"
              dynatrace_alert_id: "{{ event.payload.problem_id }}"
              dynatrace_alert_impact: "{{ event.payload.impact }}"
              dynatrace_alert_url: "{{ event.payload.url }}"

    - name: Run Disk Remediation Job
      condition: event.payload.state == 'OPEN' and event.payload.text == 'Low Disk Space problem'
      action:
        run_workflow_template:
          name: '[WF] Remediate Cloud Machine DISK'
          organization: Default
          job_args:
            extra_vars:
              dynatrace_alert_severity: "{{ event.payload.severity }}"
              dynatrace_alert_id: "{{ event.payload.problem_id }}"
              dynatrace_alert_impact: "{{ event.payload.impact }}"
              dynatrace_alert_url: "{{ event.payload.url }}"
