---
- name: Listen for events on a webhook
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:

    - name: Debug watches event
      condition:   event.payload.text == "Watches-eShop application problem"
      action:
        run_job_template:
          name: 'Launch Watches Workflow'
          organization: Default
          job_args:
            extra_vars:
              # dynatrace_alert_text: "{{ event.payload.text }}"
              # dynatrace_alert_id: "{{ event.payload.problem_id }}"
              # dynatrace_alert_title: "{{ event.payload.title }}"
              # dynatrace_alert_severity: "{{ event.payload.severity }}"
              # dynatrace_alert_url: "{{ event.payload.url }}"
              # dynatrace_alert_impact: "{{ event.payload.impact }}"
              # dynatrace_alert_tags: "{{ event.payload.tags }}"
              # dynatrace_alert_root_cause: "{{ event.payload.rootCause }}"
              # dynatrace_alert_root_state: "{{ event.payload.state }}"
              # dynatrace_alert_root_event_type: "{{ event.payload.eventType }}"
              # dynatrace_alert_root_event_id: "{{ event.payload.eventID }}"

    - name: Run CPU Remediation Job
      condition: event.payload.state == 'OPEN' and event.payload.text == 'CPU problem' and event.payload.impact == 'CPU saturation on Host cloud-demo-machine'  
      action:
        # run_workflow_template:
        #   name: '[WF] Remediate Cloud Machine CPU'
        run_job_template:
          name: 'E2E - CPU Remediation'
          organization: Default
          job_args:
            extra_vars:
              dynatrace_alert_severity: "{{ event.payload.severity }}"
              dynatrace_alert_id: "{{ event.payload.problem_id }}"
              dynatrace_alert_impact: "{{ event.payload.impact }}"
              dynatrace_alert_url: "{{ event.payload.url }}"

    - name: Run Disk Remediation Job
      condition: event.payload.state == 'OPEN' and event.payload.text == 'Low Disk Space problem'
      action:
        # run_workflow_template:
        #   name: '[WF] Remediate Cloud Machine DISK'
        run_job_template:
          name: 'E2E - DISK Remediation'
          organization: Default
          job_args:
            extra_vars:
              dynatrace_alert_severity: "{{ event.payload.severity }}"
              dynatrace_alert_id: "{{ event.payload.problem_id }}"
              dynatrace_alert_impact: "{{ event.payload.impact }}"
              dynatrace_alert_url: "{{ event.payload.url }}"
